### ISSUE TITLE
initialization error when autoinstrumenting quemu-based docker image builder

### ISSUE THREAD

**Issue by ihudak** [plengauer/opentelemetry-bash#202]
#20 0.727 /bin/sh: 19: /usr/bin/opentelemetry_shell_api.sh: cannot open /proc/0/cmdline: No such file

configurator:
https://github.com/ihudak/bookstore/blob/master/agents/scripts/set_bash_instrumentation.sh#L45

call in the Docker file:
https://github.com/ihudak/bookstore/blob/master/agents/Dockerfile#L50

the same error is on arm64 and x64 quemu vms

**Comment by plengauer** [comment]
@ihudak pls confirm with version 4.2.1

**Comment by ihudak** [comment]
it works! Thanks a lot!:

https://pae32231.dev.dynatracelabs.com/#trace;gtf=today;gf=all;traceId=fe1ce10d1f79235cf47cd710582d59cc;timeframe=custom1712481754409to1712481874417;spanId=450b658bb0fa30c6
