### ISSUE TITLE
Inject into children from env

### ISSUE THREAD

**Issue by plengauer** [plengauer/opentelemetry-bash#217]

**Comment by plengauer** [comment]
this will be particularly interesting because we have to not inject if there is some signal fuckery, and also we have to somehow transport the otel config into it

**Comment by plengauer** [comment]
look at https://github.com/plengauer/opentelemetry-bash/blob/main/src/usr/bin/opentelemetry_shell.custom.inner.sh

probaly just another mentioning env.

however, there is a complication, we shouldnt inject if there are signal arguments used.

**Comment by plengauer** [comment]
also please include a test using the -i option

**Comment by ihudak** [comment]
exclude injection for -i and signals. find
