### ISSUE TITLE
commands in if,then,else,case aren't instrumented

### ISSUE THREAD

**Issue by ihudak** [plengauer/opentelemetry-bash#50]
1. If the otel initializer is in an if-statement, it doesn't work:

```
if [ "$(echo $OTEL_TOKEN_SHELL | cut -c 1-7)" != "blah." ]; then
  OTEL_TOKEN_SHELL=$(echo "$OTEL_TOKEN_SHELL" | base64 -d);
   . /usr/bin/opentelemetry_shell.sh;
  otel_instrument echo;
fi
echo "BOO" # no span will be created
```

2. if the hotel initializer is in the root part of the script, and if the script contains "if-then-else" or "case", it doesn't instrument commands inside of the if/case:
```
. /usr/bin/opentelemetry_shell.sh
otel_instrument echo
if [ "$(echo $OTEL_TOKEN_SHELL | cut -c 1-7)" != "blah." ]; then
  OTEL_TOKEN_SHELL=$(echo "$OTEL_TOKEN_SHELL" | base64 -d);
 echo "BOO"; # no span will be created
fi
```

**Comment by plengauer** [comment]
my first thoughts are that ifs may create subshells, and unfortunately aliases in subshells (the magic behind instrumentations) do not propagate back to the root shell. let me write a test for that ...

**Comment by plengauer** [comment]
I've added tests for both scenarios: https://github.com/plengauer/opentelemetry-bash/tree/commands-in-ifthenelsecase-arent-instrumented. both pass without problems. are u sure there is not something else going on?

**Comment by ihudak** [comment]
interesting...
when I just moved it out of "if", I got spans (only until the following "if" in the script).
will look further

**Comment by plengauer** [comment]
ill merge the tests, they are good tests to have nonetheless
